#' Create a conc_logM column from conc_uM or conc_nM columns
#'
#' @param df A dataframe containing either a column called "conc_nM" or a column
#'   called "conc_uM", representing concentration in nanomolar or micromolar
#'   units respectively.
#'
#' @return The same dataframe with an additional column "conc_logM" representing
#'   concentration in log10(molar) units.
#' @export
#'
#' @examples
#' df <- data.frame("treatment" = c("foo", "bar", "baz"),
#'                  "conc_nM" = c(1, 10, 100))
#' make_log_conc(df)
make_log_conc <- function(df){
  tryCatch({ # try to convert from conc_uM
    df |> dplyr::mutate(conc_logM = log10(.data$conc_uM/1e6))},
    error = function(e){ # if no conc_uM, try to convert from conc_nM
      df |>  dplyr::mutate(conc_logM = log10(.data$conc_nM/1e9))})}

#' Convert an Excel file to csv.
#' @param excel_path Path to the Excel file. The file can be .xls or .xlsx
excel_to_csv <- function(excel_path){
  excel_data <- excel_path |> readxl::read_excel()
  csv_path <- excel_path |> tools::file_path_sans_ext() |> paste0(".csv")
  readr::write_csv(excel_data, csv_path)
}

#' Convert all Excel files in a directory to csv.
#'
#' `dir_excel_to_csv()` finds any files with .xls or .xlsx extensions in a
#' directory and attempts to create .csv versions using `excel_to_csv`. Does
#' nothing if no Excel files are present.
#'
#' @param dir The directory containing Excel files to convert.
#' @export
dir_excel_to_csv <- function(dir){
  excel_filenames <- c(list.files(dir, pattern = "^[[:alnum:]].*.xls"))
  purrr::walk(excel_filenames, excel_to_csv)
}

#' Import a csv file of the type generated by Thermo SelectScreen.
#'
#' `import_selectscreen()` expects to receive a Thermo SelectScreen results
#' file. It uses [readr::read_csv()]'s `name_repair="universal"` option to make
#' the column names unique and syntactic, then renames columns commonly used in
#' dose-response analysis to simpler, more readable names:
#'
#' * "Compound.Name" -> "treatment"
#' * "Kinase" -> "target"
#'
#' The two untidy "% Inhibition" columns are pivoted to one tidy
#' "pct_inhibition" column, the "Compound.Conc" column (which Thermo indicates
#' is in nM units) is converted to log10(molar), and an "activity" column is
#' generated by subtracting the percent inhibition from 100.
#' @param input_filename Path to file to import. `import_selectscreen()` expects
#'   the type of file that Thermo SelectScreen offers as a csv download as of
#'   2023, with the column names unedited. It expects the following columns:
#'
#'   * Compound.Name
#'   * Kinase
#'   * % Inhibition 1
#'   * % Inhibition 2
#' @return The imported table as a tibble.
#' @export
#'
import_selectscreen <- function(input_filename){
  readr::read_csv(input_filename, name_repair = "universal") |>
    # rename relevant columns to common names
    dplyr::rename(treatment = .data$Compound.Name) |>
    dplyr::rename(target = .data$Kinase) |>
    # tidy by pivoting duplicates to one measurement per row
    tidyr::pivot_longer(cols = c(.data$..Inhibition.1, .data$..Inhibition.2),
                        names_to = NULL, values_to = "pct_inhibition") |>
    # convert conc to log molar and convert percent inhibition to activity
    dplyr::mutate(conc_logM = nM_to_logM(.data$Compound.Conc)) |> # conc is nM
    dplyr::mutate(activity = 100 - .data$pct_inhibition)
}
